// 3474. Lexicographically Smallest Generated String
// Hard
// Topics
// premium lock icon
// Companies
// Hint
// You are given two strings, str1 and str2, of lengths n and m, respectively.

// A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

// If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
// If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
// Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

// Example 1:

// Input: str1 = "TFTF", str2 = "ab"

// Output: "ababa"

// Explanation:

// The table below represents the string "ababa"
// Index	T/F	Substring of length m
// 0	'T'	"ab"
// 1	'F'	"ba"
// 2	'T'	"ab"
// 3	'F'	"ba"
// The strings "ababa" and "ababb" can be generated by str1 and str2.

// Return "ababa" since it is the lexicographically smaller string.

// Example 2:

// Input: str1 = "TFTF", str2 = "abc"

// Output: ""

// Explanation:

// No string that satisfies the conditions can be generated.

// Example 3:

// Input: str1 = "F", str2 = "d"

// Output: "a"

 

// Constraints:

// 1 <= n == str1.length <= 104
// 1 <= m == str2.length <= 500
// str1 consists only of 'T' or 'F'.
// str2 consists only of lowercase English characters.

// solu =
class Solution {
public:
    string generateString(string str1, string str2) {
        
        // ------------------------------------------
        // STEP 1: Get sizes
        // ------------------------------------------
        int n = str1.size();   // length of str1 (T/F string)
        int m = str2.size();   // length of pattern string
        
        
        // ------------------------------------------
        // STEP 2: Final word length
        // ------------------------------------------
        // Each index i in str1 corresponds to a substring
        // of length m starting at i
        // So total length = n + m - 1
        int len = n + m - 1;
        
        
        // ------------------------------------------
        // STEP 3: Initialize word with '?'
        // ------------------------------------------
        // '?' means "not assigned yet"
        // We DON'T directly use 'a' here because:
        // - we must distinguish between "free positions"
        //   and "forced positions"
        string word(len, '?');
        
        
        // ------------------------------------------
        // STEP 4: Track fixed positions
        // ------------------------------------------
        // fixed[i] = true means:
        // this index was assigned due to a 'T' constraint
        // and should NOT be modified later
        vector<bool> fixed(len, false);
        
        
        // --------------------------------------------------
        // STEP 5: Apply all 'T' constraints (HARD constraints)
        // --------------------------------------------------
        // If str1[i] == 'T', then:
        // substring starting at i MUST equal str2
        
        for(int i = 0; i < n; i++) {
            if(str1[i] == 'T') {
                
                for(int j = 0; j < m; j++) {
                    
                    // If already assigned and mismatch → impossible
                    if(word[i + j] != '?' && word[i + j] != str2[j]) {
                        return "";
                    }
                    
                    // Assign character
                    word[i + j] = str2[j];
                    
                    // Mark as fixed (cannot be changed later)
                    fixed[i + j] = true;
                }
            }
        }
        
        
        // --------------------------------------------------
        // STEP 6: Fill remaining '?' with 'a'
        // --------------------------------------------------
        // Why 'a'?
        // Because we want lexicographically smallest string
        
        for(int i = 0; i < len; i++) {
            if(word[i] == '?') {
                word[i] = 'a';
            }
        }
        
        
        // --------------------------------------------------
        // STEP 7: Handle 'F' constraints (SOFT constraints)
        // --------------------------------------------------
        // If str1[i] == 'F', then:
        // substring starting at i must NOT equal str2
        
        for(int i = 0; i < n; i++) {
            if(str1[i] == 'F') {
                
                // Check if current substring matches str2
                bool match = true;
                
                for(int j = 0; j < m; j++) {
                    if(word[i + j] != str2[j]) {
                        match = false;
                        break;
                    }
                }
                
                
                // If it matches → we must BREAK it
                if(match) {
                    
                    bool changed = false;
                    
                    // Try modifying from RIGHT → LEFT
                    // Why?
                    // Changing later characters keeps string lexicographically smaller
                    
                    for(int j = m - 1; j >= 0; j--) {
                        
                        int pos = i + j;  // actual index in word
                        
                        // We CANNOT modify positions fixed by 'T'
                        if(fixed[pos]) continue;
                        
                        
                        // Try replacing with smallest possible character
                        // that is DIFFERENT from str2[j]
                        
                        for(char c = 'a'; c <= 'z'; c++) {
                            
                            if(c != str2[j]) {
                                word[pos] = c;
                                changed = true;
                                break;
                            }
                        }
                        
                        // Stop once we successfully changed one position
                        if(changed) break;
                    }
                    
                    // If we couldn't change anything → impossible
                    if(!changed) return "";
                }
            }
        }
        
        
        // --------------------------------------------------
        // STEP 8: Return final answer
        // --------------------------------------------------
        return word;
    }
};

// Time: O(n * m * 26)
// Space: O(n + m)
